### ISSUE TITLE
New gpg key codepath may not work with older PE tarballs

### ISSUE THREAD

**Issue by dhgwilliam** [oscar-stack/vagrant-pe_build#122]
the fix for #120 (commit dfedd3fdc4864040babcdc8526df005e0d4320bc) may not have the intended effect all the time... A colleague ran in to issues using the new key with the PE 2015.3.3 tarball she downloaded from the S3 bucket... Not sure if this is a OSCAR problem or a Puppet RelEng problem... Will ask for more details from colleague

**Comment by terrimonster** [comment]
Hello! On the older version of oscar, no problems installing PE on a master instance. On a colleague's instance using the brand new oscar, it bombed because the GPG was incorrect. Here's the pe_build.yaml:

---
pe_build:
  version: 2015.3.3
  download_root: "https://s3.amazonaws.com/pe-builds/released/:version"

**Comment by terrimonster** [comment]
Imagine that example up there indented properly.

**Comment by Sharpie** [comment]
Thanks for the report! Could you let me know which OS the failing tarballs were for? I checked a few out when writing the patch and the GPG path seems consistent between at least Ubuntu and CentOS.

**Comment by Sharpie** [comment]
@terrimonster @dhgwilliam On Friday afternoon, we found a couple of issues related to the GPG:

  - #123: A bug introduced by the fix that affects installations on cloud environments where `shared_installer = false` is being used. This results in a "no implicit conversion of nil into String" error message during PE installation. Local installations on VirtualBox are unaffected.

  - #124: An issue with the updated GPG key downloaded from https://apt.puppetlabs.com/pubkey.gpg that causes some RedHat installations to fail with "Public key for ... is not installed".

I'm planning a release for early this week to address both of the above issues, but I'm not sure they're the same things your users were reporting. If you could provide Vagrant logs showing the errors, that will help me make sure the next release fixes these issues.

**Comment by terrimonster** [comment]
Here is vagrant debug mode for where the key gets nabbed:

DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: run_install
DEBUG guest: Checking in: redhat
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: run_install in linux
 INFO guest: Execute capability: run_install [#<Vagrant::Machine: pemaster (VagrantPlugins::ProviderVirtualBox::Provider)>, "/vagrant/.pe_build/puppet-enterprise-2015.3.3-el-7-x86_64", "/vagrant/.pe_build/answers/pemaster.txt", {:use_pem=>false}] (redhat)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: if [ -e /vagrant/.pe_build/puppet-enterprise-2015.3.3-el-7-x86_64/gpg ]; then
  curl https://apt.puppetlabs.com/pubkey.gpg > /vagrant/.pe_build/puppet-enterprise-2015.3.3-el-7-x86_64/gpg/GPG-KEY-puppetlabs
fi
 (sudo=true)

Relevant resulting errors that kill the vagrant up:

warning: /vagrant/.pe_build/puppet-enterprise-2015.3.3-el-7-x86_64/packages/el-7-x86_64/pe-client-tools-1.0.2-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 4bd6ec30: NOKEY
Public key for pe-client-tools-1.0.2-1.el7.x86_64.rpm is not installed
warning: /var/cache/yum/x86_64/7/base/packages/libjpeg-turbo-1.2.90-5.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for libjpeg-turbo-1.2.90-5.el7.x86_64.rpm is not installed
Public key for libxml2-2.9.1-6.el7_2.3.x86_64.rpm is not installed
--------------------------------------------------------------------------------
Total                                              114 MB/s | 212 MB  00:01
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-2.1511.el7.centos.2.10.x86_64 (@anaconda)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Retrieving key from file:/vagrant/.pe_build/puppet-enterprise-2015.3.3-el-7-x86_64/gpg/GPG-KEY-puppetlabs


The GPG keys listed for the "Puppet Enterprise Installer" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: puppet-agent-1.3.6-1.el7.x86_64
 GPG Keys are configured as: file:/vagrant/.pe_build/puppet-enterprise-2015.3.3-el-7-x86_64/gpg/GPG-KEY-puppetlabs


========================================================================


========================================================================


Stderr from the command:

!! ERROR: Package installation failed

**Comment by Sharpie** [comment]
@terrimonster Awesome. That looks like the error message caused by issue #124.

I've yanked version 0.15.2 from Rubygems, so it shouldn't be installable any more. A 0.15.3 release should be coming this afternoon or tomorrow morning which resolves the issues with the GPG fix. Apologies for the disruption!

**Comment by Sharpie** [comment]
Version 0.15.3 has been shipped which addresses these issues.
