### ISSUE TITLE
Add `series` to the README documentation

### ISSUE THREAD

**Issue by Iristyle** [oscar-stack/vagrant-pe_build#128]
`series` is supported under `pe_bootstrap`, but missing from the README - https://github.com/oscar-stack/vagrant-pe_build#pe_bootstrap-provisioner-settings

**Comment by Sharpie** [comment]
Updated the README in a7ae76a with a note about the `series` setting and how it can be interpolated into `version_file` and `download_url` along with the `version` setting.
