### ISSUE TITLE
Plugin not using shared directory to find PE tarball

### ISSUE THREAD

**Issue by mschuchard** [oscar-stack/vagrant-pe_build#129]
I have in my Vagrantfile:

```
config.pe_build.version = '2016.4.2'
config.vm.box = 'centos/7'
```

and inside the same directory as the Vagrantfile:

```
puppet-enterprise-2016.4.2-el-7-x86_64.tar.gz
```

which I have also confirmed is being synced over to `/vagrant`. Despite this, I get the error:

```
Cannot fetch installer puppet-enterprise-2016.4.2-el-7-x86_64.tar.gz; no download source available.

Installers available for use:
The Puppet Enterprise installer puppet-enterprise-2016.4.2-el-7-x86_64.tar.gz
is not available. Please set the `download_root` config option to a valid
mirror, or add the installer yourself by using the `vagrant pe-build copy`
command. Downloads for Puppet Enterprise are available for download at
https://puppetlabs.com/puppet/puppet-enterprise/
```

even though the documentation for `config.pe_build.shared_installer` states:

> Description: Whether to run PE installation using installers and answers shared using the /vagrant directory. If set to false, resources will be downloaded remotely from download_root to the home directory of whichever user account Vagrant is using. Defaults to true.

Is the proper workaround for this issue to just:

```
config.pe_build.download_root = 'file:///vagrant
```

**Comment by Sharpie** [comment]
Ah. The docs for `shared_installer` are lacking in specificity, `/vagrant` is the name of the mount that is used to share the files, the location is actually a directory tree nested under `.pe_build`. This setting is primarily used when installing PE to a cloud environment such as AWS, vSphere or OpenStack as rsyncing a ~300 MB tarball up to the machine from localhost can take a significant amount of time.

What you'll want to do is drop the tarball into `~/.vagrant.d/pe_builds`. This can also be accomplished by running the `vagrant pe-build copy` command as suggested by the error message:

    vagrant pe-build copy puppet-enterprise-2016.4.2-el-7-x86_64.tar.gz

**Comment by mschuchard** [comment]
Thanks for the info. Is there some way to automate this from within the Vagrantfile instead of a manual step from the Vagrant CLI? Would my suggested workaround above accomplish this? I want to minimize dependencies for distributing the Vagrantfile.

**Comment by mschuchard** [comment]
So I did try
```
config.pe_build.download_root = 'file://${Dir.pwd}'
```
and it did seem successful in automating the tarball location, but now there is an error message:
```
bash: line 3: /vagrant/.pe_build/puppet-enterprise-2016.4.2-el-7-x86_64/puppet-enterprise-installer: No such file or directory
```
However:
```
ls .pe_build/puppet-enterprise-2016.4.2-el-7-x86_64/puppet-enterprise-installer 
.pe_build/puppet-enterprise-2016.4.2-el-7-x86_64/puppet-enterprise-installer
```

**Comment by mschuchard** [comment]
`config.pe_build.download_root = "file://#{Dir.pwd}"` does indeed work great at automating that part.

**Comment by mschuchard** [comment]
By the way, this plugin is having a lot of difficulty with using files that are generated during `:pe_bootstrap` like the answers file or the post-install manifest. I kept having to reload and reprovision the vm for the file to sync over.

**Comment by Sharpie** [comment]
Hmm. I've never observed any flakiness with syncing answer files or installers. Are you running VMs under VirtualBox?

**Comment by mschuchard** [comment]
Yes. I have worked around this by copying the answers file and doing:
```
pe.answer_file = 'answers.txt'
```
as documented. I also cleaned up the post install manifest and dropped this into a pre-bootstrap shell provisioner:
```
echo "service { 'pe-puppetserver': ensure => running }

file { '/etc/puppetlabs/puppet/autosign.conf':
  ensure  => file,
  content => \"pe-internal-dashboard\nmaster\n*\",
  owner   => 'root',
  group   => 'pe-puppet',
  mode    => '0644',
  notify  => Service['pe-puppetserver'],
}" > /vagrant/.pe_build/post-install/master.pp
```
Now everything works great, EXCEPT during the `:pe_agent` bootstrap, the puppet agent is not being executed at the end, so there is no cert request to the master and:
```
==> master: No pending signing request for node1 on master. Skipping autosign.
```
If I ssh into my client `node1`, I get the dreaded mismatched SSL cert error:
```
[vagrant@node1 ~]$ puppet agent -t
Info: Creating a new SSL key for node1
Info: Caching certificate for ca
Info: Caching certificate for node1
Error: Could not request certificate: The certificate retrieved from the master does not match the agent's private key.
Certificate fingerprint: 92:D8:E1:CA:44:59:E8:1D:E1:24:53:EE:57:11:8C:BB:9C:DD:E4:51:0A:8B:95:DC:9B:9C:15:4F:25:D4:DB:40
```

**Comment by mschuchard** [comment]
Couple updates:
- Event though the plugin output says the client was not autosigned, it actually was. So no functionality problem there; just diagnostic.
- The cert issues were because I forgot to `sudo` inside Vagrant. Disregard.

**Comment by Sharpie** [comment]
> Event though the plugin output says the client was not autosigned, it actually was. So no functionality problem there; just diagnostic.

This likely happened because the `pe_bootstrap` provider defaults to configuring master installs with a liberal autosign.conf that accepts all incoming cert requests. So, by the time the `pe_agent` provisioner shelled over to sign the cert, it had already been signed. So, the provisioner no-opped with the "No pending signing request" message.

This behavior around `autosign.conf` can be disabled by setting the `autosign` parameter of the `pe_bootstrap` provisioner to `false`. This parameter appears to be undocumented, I'll close this issue out when the docs are updated.
