### ISSUE TITLE
Add DISABLE_ANALYTICS=1 to installer invocation in debug-kit

### ISSUE THREAD

**Issue by nmburgan** [oscar-stack/vagrant-pe_build#146]
PE 2019.0.2 will have an option to disable sending installer analytics by defining the DISABLE_ANALYTICS environment variable (e.g. DISABLE_ANALYTICS=1 ./puppet-enterprise-installer).  Nick Walker would like to add this to the installer invocation in the debug-kit.

**Comment by Sharpie** [comment]
Thanks for the heads up. We'll get that added in the release that adds 2019.0.2 settings.

**Comment by Sharpie** [comment]
Shipped in 0.18.2.
