### ISSUE TITLE
vagrant-pe_build should use trivial passwords for databases

### ISSUE THREAD

**Issue by pizzaops** [oscar-stack/vagrant-pe_build#50]
Currently, vagrant-pe_build uses randomized passwords for console databases, etc.

This is an inconvenience when trying to debug database issues - there's no need to have a secure password in this context.

It'd be great if pe_build used a trivial, easy password (say, `puppetlabs`) for the databases.

**Comment by Sharpie** [comment]
Closing this out as modern PE versions no longer default to accepting passwords for the databases and rely exclusively on certificates for authentication.

This historic workaround for this has been to run `psql` as the `pe-postgres` user --- this account is the DB superuser and thus gets access to any PE database when connecting locally.
