### ISSUE TITLE
Windows hosts don't respect hostnames for certnames

### ISSUE THREAD

**Issue by metcalfc** [oscar-stack/vagrant-pe_build#51]
Because Windows hosts don't use the answer file I can make the certname be a fqdn without making the Vagrant name a fqdn which is a pain.

```
vagrant up server2008r2a
vagrant up server2008r2a.puppetlabs.vm
```

I'm trying to move the SE demo environment to a more realistic world with FQDNs. It would be great if the hostame in the vms.yaml could be used on Windows if it existed (otherwise default to machine name).

**Comment by Sharpie** [comment]
`config.vm.hostname` might not help here since Windows rejects attempts to set a FQDN as the hostname. So, hostnames must be actual hostnames.

**Comment by Sharpie** [comment]
This can probably be accomplished through pe_agent install options (#96) and special handling of the certname option (#106).

**Comment by metcalfc** [comment]
Wow this is ancient and I'm cleaning up so I'll close this. Feel free to open it again.
