### ISSUE TITLE
Windows 7 permission denied 

### ISSUE THREAD

**Issue by pearcec** [oscar-stack/vagrant-pe_build#60]
Get the following error during provisioning pe_bootstrap for role master.  Anyone have any thoughts?

<pre>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<PEBuild::Transfer::OpenURI::DownloadFailed: An error occurred w
hile trying to download the given resource (http://localhost/rep
os/Puppet//puppet-enterprise-3.1.0-el-6-x86_64.tar.gz),
and the transfer could not complete. The error message generated was "Permission
 denied - (C:/Users/pearcec/AppData/Local/Temp/open-uri20140520-5004-1hx7fqn, C
:/Users/pearcec/.vagrant.d/pe_builds/puppet-enterprise-3.1.0-el-6-x86_64.tar.gz
)".>
ERROR vagrant: An error occurred while trying to download the given resource (ht
tp://localhostm/repos/Puppet//puppet-enterprise-3.1.0-el-6-x86_64
.tar.gz),
and the transfer could not complete. The error message generated was "Permission
 denied - (C:/Users/pearcec/AppData/Local/Temp/open-uri20140520-5004-1hx7fqn, C
:/Users/pearcec/.vagrant.d/pe_builds/puppet-enterprise-3.1.0-el-6-x86_64.tar.gz
)".
ERROR vagrant: C:/Users/pearcec/.vagrant.d/gems/gems/vagrant-pe_build-0.8.7/lib
/pe_build/transfer/open_uri.rb:29:in `rescue in copy'
 INFO interface: error: An error occurred while trying to download the given res
ource (http://localhost/repos/Puppet//puppet-enterprise-3.1.0-el
-6-x86_64.tar.gz),
and the transfer could not complete. The error message generated was "Permission
 denied - (C:/Users/pearcec/AppData/Local/Temp/open-uri20140520-5004-1hx7fqn, C
:/Users/pearcec/.vagrant.d/pe_builds/puppet-enterprise-3.1.0-el-6-x86_64.tar.gz
)".
An error occurred while trying to download the given resource (http://localhost/repos/Puppet//puppet-enterprise-3.1.0-el-6-x86_64.tar.gz),
and the transfer could not complete. The error message generated was "Permission
 denied - (C:/Users/pearcec/AppData/Local/Temp/open-uri20140520-5004-1hx7fqn, C
:/Users/pearcec/.vagrant.d/pe_builds/puppet-enterprise-3.1.0-el-6-x86_64.tar.gz
)".
 INFO interface: Machine: error-exit ["PEBuild::Transfer::OpenURI::DownloadFaile
d", "An error occurred while trying to download the given resource (http://localhost/repos/Puppet//puppet-enterprise-3.1.0-el-6-x86_64.tar.gz),\
nand the transfer could not complete. The error message generated was \"Permissi
on denied - (C:/Users/pearcec/AppData/Local/Temp/open-uri20140520-5004-1hx7fqn,
 C:/Users/pearcec/.vagrant.d/pe_builds/puppet-enterprise-3.1.0-el-6-x86_64.tar.
gz)\"."]
</pre>

**Comment by liger1978** [comment]
Still an issue on Windows.  How about using `FileUtils.cp` and `FileUtils.rm` (with a warning if the latter fails) instead of `FileUtils.mv` at: https://github.com/adrienthebo/vagrant-pe_build/blob/master/lib/pe_build/transfer/open_uri.rb#L25-L26 ?

**Comment by Sharpie** [comment]
I haven't hit this personally, since I don't use Windows as my primary environment, but I've seen the issue happen at least once. Optimistically marking this to be fixed in the next release since it sounds like we just need to adjust how archives are created and moved.

**Comment by DrmCtchr** [comment]
has this been addressed? and if so how can I get that code? I don't want to have to add work around steps for all my users. thanks in advance, D

**Comment by Sharpie** [comment]
There haven't been any fixes submitted for this yet. I'm planning to do a "Windows bug bash" release focused on Windows fixes once I get done shoring up support for PE 2015.x agent installation.

If anyone wants to submit a PR to fix this issue, I'd be happy to review it!

**Comment by Sharpie** [comment]
Built a VM turducken yesterday (Vagrant inside of Windows inside of Vagrant inside of OS X) during #puppethack and tested a fix for this. It will go out in a patch release this week.

**Comment by Sharpie** [comment]
Version 0.13.6 has been shipped and includes this fix.
